### ISSUE TITLE
Skipping meta-data and run filter only on the not YAML part

### ISSUE THREAD

**Issue by NMarkgraf** [sergiocorreia/panflute#101]
Maybe I am blind or stupid,

but is there a simple way to run a filter only on the not meta-data part?

Yours
Norman

**Comment by NMarkgraf** [comment]
Could it be that easy:

return run_filter(... doc=doc.content ...) 

???

**Comment by sergiocorreia** [comment]
The way `.walk()` and thus run_filter knows what children element a given element has is via the `_children` property.

So a quick hack might be to add a line in the prepare() function of the filter that does `doc._children = ['content']`  (instead of the default `_children = ['metadata', 'content']`).

But of course this is a bit hackish, so an easier solution might be useful.
