### ISSUE TITLE
Inprecise metadata yaml vs indoc yaml INTEGER marshalling

### ISSUE THREAD

**Issue by blaggacao** [sergiocorreia/panflute#132]
```yaml
# Indoc yaml
domain:
 -
   - qmux
   - "="
   - 47
```
renders: `[['project_id', '=', 47]]`

```yaml
# Metadata yaml
domain:
 -
   - qmux
   - "="
   - 47
```
renders: `[['project_id', '=', '47']]` **wrong**, note the quote arround `47`

I assume that the `get_metadata` marshalls to a string on the `MetaString` test, while it correctly should marshall to an integer (or even float).

**Comment by sergiocorreia** [comment]
This is limitation external to panflute. If you run `pandoc -t json yourfile.md` you'll see that pandoc sends the numbers as strings inside of MetaInline types:

```json
{"t":"MetaInlines","c":[{"t":"Str","c":"42"}]}
```

Because panflute works on JSON received from pandoc, there's no easy way to know for sure that a value is an integer/float instead of a string (besides guessing via e.g. the `isdigit()` method).

When I need a workaround (e.g. when I need to read the metadata before pandoc runs) I use a preprocessor. For instance, [pandocmk](https://github.com/sergiocorreia/pandocmk/tree/master/pandocmk) (useful if you get tired typing many pandoc options again and again) just reads the YAML directly.

**Comment by blaggacao** [comment]
Ok, got it, so I'll do type casting downstream. Thanks!
