### ISSUE TITLE
update official documentation site

### ISSUE THREAD

**Issue by wgroeneveld** [sergiocorreia/panflute#180]
Hi,

I used a panflute filter to convert a longtable to a table for my scientific papers that are in two-column mode. However, these things are horribly broken since upgrading from panflute 1.11 and pandoc 2.9 to panflute 2.0.5 and pandoc 2.11.3. 

For starters, I used to grab the caption with:

```
    def caption():
        cap = stringify(Para(*elem.caption))[0:-2]  # 2 newlines to omit para
        return '\\caption{' + cap + '\\label{' + labelify(cap, 'table') + '}}\n'
```

That produces `TypeError: panflute.elements.Para() argument after * must be an iterable, not Caption` now. My fix for this is `cap = stringify(*elem.caption.content)` - although it's a bit of a guess.
Then, we move on to:

`for align in elem.alignment` - that seems to be completely gone, when I inspect the panflute 2.x source code, but it's **still there in the docs**?? Is the docs correctly updated at http://scorreia.com/software/panflute/_modules/panflute/elements.html#Table ? This is very confusing! 
Now I need to grab it using `colspec`. 

Furthermore, the `header` attribute seems to be missing, but I can fiddle with `_head`, although should I since it starts with an underscore? Edit: it seems that `elem.head.content` also works. 

```
    def headers():
        result = '\\hline\n'
        for cell in elem.header.content:
            result += stringify(cell) + ' & '
        return result[0:-3] + '\\\\ [0.5ex]\n\\hline\n\\hline\n'
```

Thanks for clearing things up.

**Comment by wgroeneveld** [comment]
As an added follow-up question regarding the new table API: This is now also broken:

```
    def items():
        result = ''
        for row in elem.content:
            txt = ''
            for cell in row.content:
                txt +=  stringify(cell).replace('_', '\\_') + ' & '
            result += txt[0:-3] + '\\tabularnewline\n'
        return result
```

It seems to jam everything in a single tabular line, omitting the & ? No idea what causes it...

**Comment by sergiocorreia** [comment]
Hi Wouter,

Yes, the latest updates to pandoc (2.11) introduced large changes to the tables element, and the November [updates](https://github.com/sergiocorreia/panflute/commit/ee1349f2f8651b8bb6c338939fc3fc26050063c9) to panflute added support for it.

For instance, given a table element `e`, then `e.caption` is not a Block as before, but a `Caption` element.

About the documentation, yes,  it needs to be updated. One of the tools I use to update my website is now deprecated and I can't use it (s3_website), and right after the update I entered bereavement leave, so I won't be able to update it for at the very least a few weeks.

In the mean time, you can 

a) Use older versions of panflute/pandoc (see the panflute github readme for info)
b) see the table code https://github.com/sergiocorreia/panflute/blob/master/panflute/table_elements.py to know how to use the new table elements (I need to write a tutorial on that because it's quite complicated)

**Comment by ickc** [comment]
Another source of understanding the table ast would be icky/pantable. Look at `PanTable.to_panflute_ast` to see how it should be constructed, Eg on alignment. The new table ast is a godsend and is much more general now.

**Comment by ickc** [comment]
For building documentation, I've set up <https://panflute.readthedocs.io> which gives you doc on all tagged versions of panflute (not a lot as it is only recently been git tagged.)

(Currently <http://scorreia.com/software/panflute/> is at 1.12.4.)

**Comment by ickc** [comment]
I added a temporary doc which has the API doc auto-generated in <https://ickc.github.io/panflute/panflute.table_elements.html#panflute.table_elements.Table>

**Comment by wgroeneveld** [comment]
Great, thanks for the effort ickc! 

I managed to fix most things by reverse-engineering the source code, but the `items()` function I posted is still not working - it seems t paste everything together without the `&`, thus omitting creating a new column in LaTeX. Any ideas on that one?

**Comment by ickc** [comment]
See https://github.com/sergiocorreia/panflute/issues/197#issuecomment-917607575.
