### ISSUE TITLE
How to get output page number of an element?

### ISSUE THREAD

**Issue by Karamaz0V1** [sergiocorreia/panflute#181]
For my defense I am writing a filter to convert pandoc speaker notes (native for pptx and revealjs) to comments on a side file for beamer slides (with pdfpc). To make it work I just need to link panflute elements to the page number of the produced document.

I was wondering if there is an easy way to retrieve the page number of an element in the output document with panflute?

**Comment by sergiocorreia** [comment]
I'm not aware of any way, but it should not be impossible given that your output is tex. Might be worth it to ask in pandoc-discuss, to see if anyone knows of a general way to do it (which the can be specialized to panflute)

**Comment by ickc** [comment]
I'm classifying it as "wontfix" as the AST doesn't have this information, in particular it depends on the output format that you need to hack your way through to obtain this information (i.e. per output format, you need to implement a way to process the output enough to get this.)

Unless there's a significant interest in doing this, I suggest just closing this issue, since it is really quite beyond the scope of panflute (from a pandoc AST "manipulator" to parsing various formats directly.)

**Comment by Karamaz0V1** [comment]
It's good for me. I got around the problem by defining notes on every slides then counting.
