### ISSUE TITLE
Update to 2.12 and 2.13

### ISSUE THREAD

**Issue by gabyx** [sergiocorreia/panflute#183]
Could panflute be updated to use pandoc 2.12 and 2.13?

**Comment by sergiocorreia** [comment]
I don't see anything specific to pandoc-types, to the AST, or filters in the changelog of the new releases. What feature of 2.12-2.13 are you thinking about?

**Comment by gabyx** [comment]
I dont know :). Maybe. we should update the docs :)?

Von meinem iPhone gesendet

**Comment by ickc** [comment]
I can work on this probably on Saturday to make sure the test passes and update the doc and also release a new version, as that allows us to package the conda forge package with new pandoc version constraints.

**Comment by sergiocorreia** [comment]
I see. TBH it's better to just state support for e.g. "pandoc 2.11+" as most likely a new update won't break the code (I think only two pandoc updates have ever introduces problems, out of maybe 50+ updates).

**Comment by ickc** [comment]
The effort to improve the conda-forge panflute package is to optionally constraints pandoc versions when installing panflute, so that it is "unbreakable" if one installs panflute and pandoc from conda.

The "downside" of this is, we should properly package this updated information, and propagate that to the conda-forge feedstock.

Also, there's some misc. updates bundled together in #177. So it is also due for a minor/patch update. (Don't merge #177 yet, I want to improve one thing there first and then you can review them.)

I'm working on testing pandoc 2.12+ now.

**Comment by ickc** [comment]
See #177 for PR that add pandoc 2.12+ support.

**Comment by ickc** [comment]
It is merged to master and will be released as panflute 2.1.0 soon.

However, the only backward incompatible change is the data dir location (see #185). So panflute 2.0.x already work with pandoc 2.12+ unofficially.

Closing as the 2.1.0 will be released soon and the official support is only a formality, but is already working.

**Comment by gabyx** [comment]
Thanks for your effort!
