### ISSUE TITLE
doc.walk order of traversal 

### ISSUE THREAD

**Issue by rschram** [sergiocorreia/panflute#196]
What is the order of traversal of elements when one uses `doc.walk()`?  

I have been playing around with panflute for the first time, and from what I can see it looks like `doc.walk` is a depth-first search with a specific ordering of the visited nodes that applies a function to the terminal nodes first. (I don't know enough graph theory to comment more specifically.) It seems like a walk of [a [b] [c [d]]] will apply a function to a, b, d, c. In my case, I would like to assign a unique id to several nested Spans in a Doc based on their location in the Doc tree, so I hoped that a walk would apply a function to each node that is visited in a depth-first search in the order they are visited, that is, parents before children.

According to [this issue](https://github.com/jgm/pandoc/issues/5667), Pandoc Lua filters do not traverse in a "linear order." Does this also apply to panflute's walk of a Doc? Is there a way around this? 

Thanks for your help.

**Comment by sergiocorreia** [comment]
Hi Ryan,

This is kinda done on as depth-first but not exactly. In your example, panflute would do "b a d c". The reason is that it applies the functions to the child before doing so to the parent (there was a rationale for this that I can't recall).

Assuming you are running panflute in isolation (i.e. not using the autofilter options), then you can just:

1. Look at the code for `walk` [here](https://github.com/sergiocorreia/panflute/blob/master/panflute/base.py#L253)
2. What you need to do is create a new walk function where line 275 is moved to line 252, and then set `panflute.walk=mywalk` . Then your filter should run depth-first in the order you want.
3.

**Comment by rschram** [comment]
Thanks, I will try this and report back.
