### ISSUE TITLE
Documentation discrepancies: pandoc-filters or panflute-filters meta-data field.

### ISSUE THREAD

**Issue by reenberg** [sergiocorreia/panflute#68]
The general description of panflute ([here](http://scorreia.com/software/panflute/#comes-with-batteries-included)) indicates that you should use the meta-data field `pandoc-filters`,  however [this](http://scorreia.com/software/panflute/guide.html#running-filters-automatically) link states i more details that you should use `panflute-filters`.

I assume that the first link is a typo or legacy?

**Comment by sergiocorreia** [comment]
Yep, the first link was just a [typo](https://github.com/sergiocorreia/panflute/blob/master/panflute/autofilter.py#L31). I can't call it `pandoc-filter` because there can be many more types of Pandoc filters (written in other languages or w/other frameworks).

Let me know if you see any more typos and I'll fix them on the next update! (or feel free to send a PR request based on the [`docs`](https://github.com/sergiocorreia/panflute/tree/master/docs/source) folder).
