### ISSUE TITLE
Install via conda

### ISSUE THREAD

**Issue by kiwi0fruit** [sergiocorreia/panflute#77]
It would be nice to have panflute installable in conda (Anaconda/Miniconda). Please consider putting it to conda-forge.

By the way. I've seen your ideas about Pandoc filters distribution and came to the conclusion that it would be more concise to distribute any filters in separate pip or conda packages. Conda is welcome for distributing compiled binaries so I'm going to put even pandoc-crossref there some day.

**Comment by kiwi0fruit** [comment]
You need to create and push a conda recipie (a rather short one) and then it will be automatically built and uploaded for all platforms.

**Comment by kiwi0fruit** [comment]
### Markdown+HTML as PDF, MS Word and others killer

@sergiocorreia See the [**dream description**](https://github.com/kiwi0fruit/misc/blob/master/pdf_and_word_killer.md).

**Comment by kiwi0fruit** [comment]
https://github.com/conda-forge/panflute-feedstock

**Comment by ickc** [comment]
If I understand it correctly, specifically in <https://github.com/conda-forge/panflute-feedstock/blob/master/recipe/meta.yaml> and <https://anaconda.org/conda-forge/panflute/files>, there's no separate packages provided for Python 2 and pasteurize is not applied so that conda-forge formula is probably not going to work in Python2.

May be we could just open an issue / mention it in doc to warn people still using Python 2 to not install from conda.

**Comment by sergiocorreia** [comment]
Hi Kolen,

I've been on paternity leave lately so I haven't been very up-to-date on issues and PRs. That said, should we just drop support for py2? EOL is in half a year, and we might as well push an update that drops support now. I haven't touched py2 in a few years, but I guess a few users are still on it? (is there a way to know based on pypi stats?)

**Comment by ickc** [comment]
There's a good summary on https://python3statement.org/practicalities/

I think in short:

- requires setuptools version 24.2.0 or above
- add `python_requires='>=3.3'` or so
- tell user to have Pip ≥ 9.0

This way when Python 2 users installing panflute, pip will correctly resolve to the last Python2 supported version.

I think the problem with the current conda recipe is that currently there's no way for a Python2 end users to install it correctly, nor even to know that it is not installed correctly.

I had thought about creating a conda recipe in the past but didn't do so because the current build process is a bit complicated to translate into a conda recipe easily. (conda can auto-generate one if it is simple, but the current setup isn't.)
