### ISSUE TITLE
Building writers.

### ISSUE THREAD

**Issue by ekiim** [sergiocorreia/panflute#84]
Is there a way that we can make write a _writer_ with Panflute? 
Has anyone thought of it?
I've been reading in the pandoc documentation, and in the section [Custom Writers](https://pandoc.org/MANUAL.html#custom-writers), It talks about been able to write a writer in Lua, and make pandoc enforce it.
With pandoc we have a _pythonic_ representation of the same *AST* so, I guess we could work on enabling a way or a "standard" way of writing a writer...

Does this sounds do able?

**Comment by sergiocorreia** [comment]
We can always do this:

1. Run `pandoc --to=json ...`
2. Pipe that to panflute
3. Have a filter that can be applied to every element, creating the output
4. Use panflute's `walk()` that goes through every element
5. Instead of dumping the data back into json, save it as a text file

That said, having a filter than parses every possible element is a lot of work, so for small changes it's always easy to piggyback on other writers.

**Comment by ekiim** [comment]
I'm thinking about a Custom HTML writer, I can make an HTML filter (with XML tools), that fixes my output to the way I want but, I can't do that with latex, so the AST, it's the only common place I can get the document to output to HTML and Latex, this is why I'm considering having my own writer. 

I know It might be heavy, but may be, a _"partial writer"_, that takes certain formatted elements, and alters the AST in a way that Introduces the raw blocks that you need in the output for that case. 
This sounds like the correct way, but also sounds kind of noisy.

May be, having another run that walks the tree, at the end of the filter application, that uses a _config file_ that gives the matching rules for each panflute element, and the corresponding element in the output representation, that way we can write _quick_ writers, this will limit the scope of what is doable, but still, I think It could work, just be thinking on how to implement the module, in a way that doesn't make noise the rest of the panflute functionality but that still uses the same structures.

**Comment by burnpanck** [comment]
I'm also interested in this. I intend to write a specific docx writer for our purposes, because the standard pandoc writer of docx is too limited. Particularly, I would like to use a template, where I insert certain metadata at the right locations. With `python-docx` I can handle the necessary docx pushing, and I don't want to learn haskell :-).

@sergiocorreia: It would be great if you could elaborate a little more on your proposed workaround: How would you invoke panflute and pipe the json to it? I'm new to panflute, and did not find any information how to invoke panflute in any way other than as a filter, which means it will always go through another writer at the end, right?

**Comment by ekiim** [comment]
Yves, My first approach to this, was for `md -> html`, and what I wanted
was to be able to put attributes to certain elements...
(the idea was to be able to overload the `DefinitionList` to be able to
work with `theorem` environments and have attributes for `html` style them
as a _theorem, definition, lemma, etc.._), so I added I did a filter (I
haven't put it in github, but if you like I could upload it tonight), that
worked something like this:

```
Pythagoras {#theo:pythAlg .theorem}
 : It states that the square of the hypotenuse (the side opposite the right
angle) is equal to the sum of the squares of the other two sides.
```

And the filter would look at the end of a `term` in a `DefinitionItem` in a
`DefinitionList` (First it breaked all the `DefinitionList to have only one
`DefinitionItem` per list), and then, if the term matched the _Regex_
`/{[#a-zA-Z0-9-_\.\=\s]+}/` I would extract the block surrounded by
brakets, replace the `DefinitionList` as a `RawBlock` containing each
`html`-tag needed, and the output would look like this

```
<dl id="theo:pythAlg" class="theorem">
<dt>Pythagoras</dt>
<dd><p>It states that the square of the hypotenuse (the side opposite the
right angle) is equal to the sum of the squares of the other two
sides.</p></dd>
</dl>
```

And then Pandoc would process the rest of the document as it normally does.

Now when It comes to `docx` files, I haven't worked with them, but I guess
you could do something slightly like that,
but you'll need to consider you'll get in the issue of the actually writing
from scratch a `docx` document...

Another Option, is to make a writer that does a recursive walk to the tree,
and use a library like [python-docx](
https://github.com/python-openxml/python-docx), and when ever you encounter
an element of `typeA` you map it the the corresponding writer function.

Or keep it simple, use pandoc to make the most of work, and start writing
`VisualBasic` macros, and after writing, execute the macros over the docx
file to style it as you wish. (this is the simplest I think).

Hope I helped.
